import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generateEPDSPdf() {
  const pdf = new jsPDF();

  pdf.setFontSize(18);
  pdf.text("MamaBalance", 14, 18);

  pdf.setFontSize(14);
  pdf.text("EPDS Summary Report", 14, 30);

  pdf.setFontSize(10);
  pdf.text("Generated by: Super Admin", 14, 38);
  pdf.text("Date Range: This Month", 14, 44);

  pdf.setFontSize(12);
  pdf.text("Key Metrics", 14, 56);

  autoTable(pdf, {
    startY: 60,
    head: [["Metric", "Value"]],
    body: [
      ["Total Mothers Screened", "3,420"],
      ["EPDS Submissions", "412"],
      ["High Risk Mothers", "124"],
      ["Moderate Risk Mothers", "680"],
      ["Low Risk Mothers", "2,616"],
    ],
  });

  pdf.addPage();

  pdf.setFontSize(14);
  pdf.text("Region-wise Breakdown", 14, 20);

  autoTable(pdf, {
    startY: 26,
    head: [["Region", "Low", "Moderate", "High"]],
    body: [
      ["Colombo", "15", "5", "3"],
      ["Galle", "13", "4", "3"],
      ["Kaduwela", "7", "4", "2"],
    ],
  });

  pdf.setFontSize(9);
  pdf.text(
    "Confidential – For Medical & Administrative Use Only",
    14,
    pdf.internal.pageSize.height - 10
  );

  pdf.save("EPDS_Report.pdf");
}
